Public Class frmPractice3

    Private Sub แบบฝกปฏบต1ToolStripMenuItem_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles แบบฝกปฏบต1ToolStripMenuItem.Click
        Dim frmMyP1 As frmPractice1 = New frmPractice1
        frmMyP1.Show()
    End Sub

   
    Private Sub แบบฝกปฏบต2ToolStripMenuItem_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles แบบฝกปฏบต2ToolStripMenuItem.Click
        Dim frmMyP2 As frmPractice2 = New frmPractice2
        frmMyP2.Show()
    End Sub

    Private Sub ใToolStripMenuItem_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ใToolStripMenuItem.Click
        Dim frmMyL1 As frmLab1 = New frmLab1
        frmMyL1.show()
    End Sub

    Private Sub ใบงานท2ToolStripMenuItem_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ใบงานท2ToolStripMenuItem.Click
        Dim frmMyL2 As frmLab2 = New frmLab2
        frmMyL2.Show()
    End Sub

    Private Sub ใบงานท3ToolStripMenuItem_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ใบงานท3ToolStripMenuItem.Click
        Dim frmMyL3 As frmLab3 = New frmLab3
        frmMyL3.Show()
    End Sub

    Private Sub ใบงานท4ToolStripMenuItem_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ใบงานท4ToolStripMenuItem.Click
        Dim frmMyL4 As frmLab4 = New frmLab4
        frmMyL4.Show()
    End Sub

    Private Sub แบบฝกปฏบต4ToolStripMenuItem_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles แบบฝกปฏบต4ToolStripMenuItem.Click
        Dim frmMyP4 As frmPractice4 = New frmPractice4
        frmMyP4.Show()
    End Sub

    Private Sub แบบฝกปฏบต5ToolStripMenuItem_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles แบบฝกปฏบต5ToolStripMenuItem.Click
        Dim frmMyP5 As frmPractice5 = New frmPractice5
        frmMyP5.Show()
    End Sub

    Private Sub ใบงานท5ToolStripMenuItem_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles ใบงานท5ToolStripMenuItem.Click
        Dim frmMyL5 As frmLab5 = New frmLab5
        frmMyL5.Show()
    End Sub
End Class